apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: jzaalpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jzaalpipelinesjavascriptdocker 
    spec:
      containers:
        - name: jzaalpipelinesjavascriptdocker 
          image: vdc01containerregistry.azurecr.io/jzaalpipelinesjavascriptdocker 
          ports:
          - containerPort: 8080